<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('comment', 'comment_quote_id_quote_id', array(
             'name' => 'comment_quote_id_quote_id',
             'local' => 'quote_id',
             'foreign' => 'id',
             'foreignTable' => 'quote',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
       
        $this->addIndex('comment', 'comment_quote_id', array(
             'fields' => 
             array(
              0 => 'quote_id',
             ),
             )); 
    }

    public function down()
    {
        $this->dropForeignKey('comment', 'comment_quote_id_quote_id');
     
        $this->removeIndex('comment', 'comment_quote_id', array(
             'fields' => 
             array(
              0 => 'quote_id',
             ),
             ));
    }
}