<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{

    public function up()
    {
        $this->createTable('comment', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'quote_id' =>
             array(
              'type' => 'integer',
              'length' => '8',
              'notnull' => '1',
             ),
             'contenu' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '',
             ),
             'auteur' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'mail' => 
             array(
              'type' => 'string',
              'notnull' => '',
              'length' => '255',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'valide' => 
             array(
              'type' => 'boolean',
              'default' => '0',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        
    }

    public function down()
    {
        $this->dropTable('comment');
    }
}