generator:
  class: sfDoctrineGenerator
  param:
    model_class:           quote
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          quote
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        batch_actions:
          delete: ~
          validate: ~
        object_actions:
          edit: ~
          delete: ~
          validate: ~
      filter:  ~
      form:    ~
      edit:    ~
